from themes.syntaxstyle import (
    xt256,
    vs,
    vs2015,
    spacemacs,
    onedark,
    one_light,
    monokai,
    nord,
    github,
    github_dark,
    far,
    tomorrow_night_blue,
    googlecode,
    atom_one_dark,
    atom_one_light,
    androidstudio,
    gruvbox_light_medium,
    gruvbox_dark_medium,
    obsidian,
    night_owl,
    grayscale,
    stackoverflow_dark,
    stackoverflow_light,
    dracula,
)

__all__ = [
    "xt256",
    "vs",
    "vs2015",
    "spacemacs",
    "onedark",
    "one_light",
    "monokai",
    "nord",
    "github",
    "github_dark",
    "far",
    "tomorrow_night_blue",
    "googlecode",
    "atom_one_dark",
    "atom_one_light",
    "androidstudio",
    "gruvbox_light_medium",
    "gruvbox_dark_medium",
    "obsidian",
    "night_owl",
    "grayscale",
    "stackoverflow_dark",
    "stackoverflow_light",
    "dracula",
]

THEMES = {
    "xt256": xt256.xt256_theme,
    "vs": vs.vs_theme,
    "vs2015": vs2015.vs2015_theme,
    "spacemacs": spacemacs.spacemacs_theme,
    "onedark": onedark.onedark_theme,
    "one_light": one_light.one_light_theme,
    "monokai": monokai.monokai_theme,
    "nord": nord.nord_theme,
    "github": github.github_theme,
    "github_dark": github_dark.github_dark_theme,
    "far": far.far_theme,
    "tomorrow_night_blue": tomorrow_night_blue.tomorrow_night_blue_theme,
    "googlecode": googlecode.googlecode_theme,
    "atom_one_dark": atom_one_dark.atom_one_dark_theme,
    "atom_one_light": atom_one_light.atom_one_light_theme,
    "androidstudio": androidstudio.androidstudio_theme,
    "gruvbox_light_medium": gruvbox_light_medium.gruvbox_light_medium_theme,
    "gruvbox_dark_medium": gruvbox_dark_medium.gruvbox_dark_medium_theme,
    "obsidian": obsidian.obsidian_theme,
    "night_owl": night_owl.night_owl_theme,
    "grayscale": grayscale.grayscale_theme,
    "stackoverflow_dark": stackoverflow_dark.stackoverflow_dark_theme,
    "stackoverflow_light": stackoverflow_light.stackoverflow_light_theme,
    "darcula": dracula.dracula_theme,
}
