from themes.syntaxstyle import (
    xt256,
    vs,
    vs2015,
    spacemacs,
    onedark,
    one_light,
    monokai,
    nord,
    github,
    github_dark,
    far,
    tomorrow_night_blue,
    googlecode,
    atom_one_dark,
    atom_one_light,
    androidstudio,
    gruvbox_light_medium,
    gruvbox_dark_medium,
    obsidian,
    night_owl,
    grayscale,
    stackoverflow_dark,
    stackoverflow_light,
    dracula,
)

__all__ = [
    "xt256",
    "vs",
    "vs2015",
    "spacemacs",
    "onedark",
    "one_light",
    "monokai",
    "nord",
    "github",
    "github_dark",
    "far",
    "tomorrow_night_blue",
    "googlecode",
    "atom_one_dark",
    "atom_one_light",
    "androidstudio",
    "gruvbox_light_medium",
    "gruvbox_dark_medium",
    "obsidian",
    "night_owl",
    "grayscale",
    "stackoverflow_dark",
    "stackoverflow_light",
    "dracula",
]

THEMES = {
    "xt256": ("Xt256", xt256.xt256_theme),
    "vs": ("Vs", vs.vs_theme),
    "vs2015": ("Vs2015", vs2015.vs2015_theme),
    "spacemacs": ("Spacemacs", spacemacs.spacemacs_theme),
    "onedark": ("Onedark", onedark.onedark_theme),
    "one_light": ("One Light", one_light.one_light_theme),
    "monokai": ("Monokai", monokai.monokai_theme),
    "nord": ("Nord", nord.nord_theme),
    "github": ("Github", github.github_theme),
    "github_dark": ("Github Dark", github_dark.github_dark_theme),
    "far": ("Far", far.far_theme),
    "tomorrow_night_blue": (
        "Tomorrow Night Blue",
        tomorrow_night_blue.tomorrow_night_blue_theme,
    ),
    "googlecode": ("Googlecode", googlecode.googlecode_theme),
    "atom_one_dark": ("Atom One Dark", atom_one_dark.atom_one_dark_theme),
    "atom_one_light": ("Atom One Light", atom_one_light.atom_one_light_theme),
    "androidstudio": ("Androidstudio", androidstudio.androidstudio_theme),
    "gruvbox_light_medium": (
        "Gruvbox Light Medium",
        gruvbox_light_medium.gruvbox_light_medium_theme,
    ),
    "gruvbox_dark_medium": (
        "Gruvbox Dark Medium",
        gruvbox_dark_medium.gruvbox_dark_medium_theme,
    ),
    "obsidian": ("Obsidian", obsidian.obsidian_theme),
    "night_owl": ("Night Owl", night_owl.night_owl_theme),
    "grayscale": ("Grayscale", grayscale.grayscale_theme),
    "stackoverflow_dark": (
        "Stackoverflow Dark",
        stackoverflow_dark.stackoverflow_dark_theme,
    ),
    "stackoverflow_light": (
        "Stackoverflow Light",
        stackoverflow_light.stackoverflow_light_theme,
    ),
    "darcula": ("Dracula", dracula.dracula_theme),
}
