name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python_version: "3.12"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Build Application
        run: |
          poetry run pyside6-rcc panktikhata/resources.qrc -o panktikhata/assets/resources.py
          poetry python pyinstaller_build.py
        
          
          
